import { Heading, List, Stack, Text } from "@chakra-ui/react";
import React from "react";

const PrivacePolicy = () => {
  return (
    <Stack gapY={50} px={{ base: 4, md: "10%" }} py={"5rem"}>
      {/* General */}
      <Heading>Privacy Policy for Fear Exposure AR</Heading>
      <Stack gapY={50}>
        <Heading size={"6xl"}>Privacy Policy</Heading>
        <Stack>
          <Text>Last updated: November 15, 2024</Text>
          <Text>
            This Privacy Policy describes Our policies and procedures on the
            collection, Use and disclosure of Your information when You Use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </Text>
          <Text>
            We Use Your Personal data to provide and improve the Service. By
            Using the Service, You agree to the collection and Use of
            information in accordance with this Privacy Policy. This Privacy
            Policy has been created with the help of the Privacy Policy
            Generator.
          </Text>
        </Stack>
      </Stack>
      {/* Interpretation and Definitions */}
      <Stack gapY={10}>
        <Heading size={"4xl"}>Interpretation and Definitions</Heading>
        <Stack gapY={5}>
          <Heading size={"2xl"}>Interpretation</Heading>
          <Text>
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </Text>
        </Stack>

        <Stack gapY={5}>
          <Heading size={"2xl"}>Definitions</Heading>
          <Stack>
            <Text>For the purposes of this Privacy Policy:</Text>
            <List.Root>
              <List.Item>
                Account means a unique account created for You to access our
                Service or parts of our Service.
              </List.Item>
              <List.Item>
                Affiliate means an entity that controls, is controlled by or is
                under common control with a party, where {'"control"'} means
                ownership of 50% or more of the shares, equity interest or other
                securities entitled to vote for election of directors or other
                managing authority.
              </List.Item>
              <List.Item>
                Application refers to Fear Exposure AR, the software program
                provided by the Company.
              </List.Item>
              <List.Item>
                Company (referred to as either {'"the Company"'}, {'"We"'},{" "}
                {'"Us"'}
                or {'"Our"'} in this Agreement) refers to Fear Exposure AR.
              </List.Item>
              <List.Item>Country refers to: Indonesia</List.Item>
              <List.Item>
                Device means any device that can access the Service such as a
                computer, a cellphone or a digital tablet.
              </List.Item>
              <List.Item>
                Personal Data is any information that relates to an identified
                or identifiable individual.
              </List.Item>
              <List.Item>Service refers to the Application.</List.Item>
              <List.Item>
                Service Provider means any natural or legal person who processes
                the data on behalf of the Company. It refers to third-party
                companies or individuals employed by the Company to facilitate
                the Service, to provide the Service on behalf of the Company, to
                perform services related to the Service or to assist the Company
                in analyzing how the Service is Used.
              </List.Item>
              <List.Item>
                Usage Data refers to data collected automatically, either
                generated by the Use of the Service or from the Service
                infrastructure itself (for example, the duration of a page
                visit).
              </List.Item>
              <List.Item>
                You means the individual accessing or Using the Service, or the
                company, or other legal entity on behalf of which such
                individual is accessing or Using the Service, as applicable.
              </List.Item>
            </List.Root>
          </Stack>
        </Stack>
      </Stack>
      {/* Collecting and Using Your Personal Data */}
      <Stack gapY={10}>
        <Heading size={"4xl"}>Collecting and Using Your Personal Data</Heading>
        <Stack gapY={5}>
          <Heading size={"2xl"}>Types of Data Collected</Heading>
          <Stack gapY={3}>
            <Heading size={"xl"}>Personal Data</Heading>
            <Stack>
              <Text>
                Our Application does not collect any personally identifiable
                information (PII).
              </Text>
              <Text>
                No information that could be Used to contact or identify You,
                such as names, email addresses, or other personal details, is
                collected, stored, or transmitted while Using Our Service.
              </Text>
              <Text>
                Any data collected is limited to anonymized, non-identifiable
                information, such as demographic trends or crash analytics, Used
                solely to improve the functionality and performance of the
                Application.
              </Text>
            </Stack>
          </Stack>
          <Stack gapY={3}>
            <Heading size={"xl"}>Usage Data</Heading>
            <Stack>
              <Text>
                When Using our iOS Application, We may collect certain Usage
                Data automatically to improve the performance and User
                experience of the Application.
              </Text>
              <Text>
                The information collected is strictly limited to anonymized
                demographic data (e.g., general location and Usage trends) and
                crash analytics to identify and resolve technical issues. This
                data does not include any personal information and cannot be
                Used to identify individual Users.
              </Text>
              <Text>
                No identifiable information, such as your {"Device's"} IP
                address, unique device ID, or browsing activity, is collected or
                stored.
              </Text>
              <Text>
                We Use this information solely to enhance the functionality and
                reliability of the Application while respecting Your privacy.
              </Text>
            </Stack>
          </Stack>
          <Stack gapY={3}>
            <Heading size={"xl"}>
              Information Collected while Using the Application
            </Heading>
            <Stack>
              <Text>
                Our Application does not collect any personal information from
                Your Device.
              </Text>
              <Text>
                While certain features of the Application may require temporary
                access to Your {"Device's"} camera or photo library to function,
                this access is limited to enabling those features directly on
                Your Device. No data is collected, stored, or transmitted to the
                Company or any external servers.
              </Text>
              <Text>
                You can manage permissions for the camera and photo library at
                any time through Your Device settings.
              </Text>
            </Stack>
          </Stack>
        </Stack>
        <Stack gapY={5}>
          <Heading size={"2xl"}>Use of Your Personal Data</Heading>
          <Stack>
            <Text>
              Our Company does not collect, retain, or process any Personal Data
              from Users. All information remains stored locally on the{" "}
              {"User's"}
              device and is not transmitted, stored, or shared with any external
              parties, including the Company, affiliates, or service providers.
            </Text>
            <Text>
              As such, We do not Use Personal Data for any of the purposes
              typically associated with data collection, such as account
              management, communication, marketing, bUsiness transfers, or data
              analysis.
            </Text>
            <Text>
              If you have any questions about this policy or our approach to
              User privacy, you can contact Us directly for clarification.
            </Text>
          </Stack>
        </Stack>
        <Stack gapY={5}>
          <Heading size={"2xl"}>Retention of Your Personal Data</Heading>
          <Text>
            Our Company does not retain any Personal Data or Usage Data from
            Users. All data associated with the application remains solely on
            the {"User's"} device and is not stored or processed by the Company.
          </Text>
        </Stack>
        <Stack gapY={5}>
          <Heading size={"2xl"}>Transfer of Your Personal Data</Heading>
          <Text>
            Our application does not transfer or process any Personal Data
            outside of Your device. All data remains stored locally on Your
            device, and no information is transmitted to the {"Company's"}{" "}
            servers or third parties.
          </Text>
        </Stack>
        <Stack gapY={5}>
          <Heading size={"2xl"}>Delete Your Personal Data</Heading>
          <Stack>
            <Text>
              You have the right to delete the Personal Data that We have
              collected about You.
            </Text>
            <Text>
              Our Service is designed to ensure that uninstalling the
              application from Your device will automatically delete the
              Personal Data associated with Your Use of the application. If
              additional steps are required to complete the deletion process,
              You will be informed within the application or through
              accompanying documentation.
            </Text>
            <Text>
              Please note, hoWever, that We may retain certain information if
              required by law or if We have a lawful basis to do so, even after
              the application is uninstalled.
            </Text>
          </Stack>
        </Stack>
        <Stack gapY={5}>
          <Heading size={"2xl"}>Disclosure of Your Personal Data</Heading>
          <Stack gapY={3}>
            <Heading size={"xl"}>Business Transactions</Heading>
            <Text>
              If the Company is involved in a merger, acquisition or asset sale,
              Your Personal Data may be transferred. We will provide notice
              before Your Personal Data is transferred and becomes subject to a
              different Privacy Policy.
            </Text>
          </Stack>
          <Stack gapY={3}>
            <Heading size={"xl"}>Law enforcement</Heading>
            <Text>
              Under certain circumstances, the Company may be required to
              disclose Your Personal Data if required to do so by law or in
              response to valid requests by public authorities (e.g. a court or
              a government agency).
            </Text>
          </Stack>
          <Stack gapY={3}>
            <Heading size={"xl"}>Other legal requirements</Heading>
            <Stack>
              <Text>
                The Company may disclose Your Personal Data in the good faith
                belief that such action is necessary to:
              </Text>
              <List.Root>
                <List.Item>Comply with a legal obligation</List.Item>
                <List.Item>
                  Protect and defend the rights or property of the Company
                </List.Item>
                <List.Item>
                  Prevent or investigate possible wrongdoing in connection with
                  the Service
                </List.Item>
                <List.Item>
                  Protect the personal safety of Users of the Service or the
                  public
                </List.Item>
                <List.Item>Protect against legal liability</List.Item>
              </List.Root>
            </Stack>
          </Stack>
        </Stack>
        <Stack gapY={5}>
          <Heading size={"2xl"}>Security of Your Personal Data</Heading>
          <Text>
            The security of Your Personal Data is important to Us, but remember
            that no method of transmission over the Internet, or method of
            electronic storage is 100% secure. While We strive to Use
            commercially acceptable means to protect Your Personal Data, We
            cannot guarantee its absolute security.
          </Text>
        </Stack>
      </Stack>
      <Stack gapY={10}>
        <Heading size={"4xl"}>{"Children's"} Privacy</Heading>
        <Stack>
          <Text>
            Our Service does not address anyone under the age of 13. We do not
            knowingly collect personally identifiable information from anyone
            under the age of 13. If You are a parent or guardian and You are
            aware that Your child has provided Us with Personal Data, please
            contact Us. If We become aware that We have collected Personal Data
            from anyone under the age of 13 without verification of parental
            consent, We take steps to remove that information from Our servers.
          </Text>
          <Text>
            If We need to rely on consent as a legal basis for processing Your
            information and Your country requires consent from a parent, We may
            require Your {"parent's"} consent before We collect and Use that
            information.
          </Text>
        </Stack>
      </Stack>
      <Stack gapY={10}>
        <Heading size={"4xl"}>Changes to this Privacy Policy</Heading>
        <Stack>
          <Text>
            We may update Our Privacy Policy from time to time. We will notify
            You of any changes by posting the new Privacy Policy on this page.
          </Text>
          <Text>
            We will let You know via email and/or a prominent notice on Our
            Service, prior to the change becoming effective and update the{" "}
            {'"Last updated"'} date at the top of this Privacy Policy.
          </Text>
          <Text>
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </Text>
        </Stack>
      </Stack>
      <Stack gapY={10}>
        <Heading size={"4xl"}>Contact Us</Heading>
        <Stack>
          <Text>
            If you have any questions about this Privacy Policy, You can contact
            Us:
          </Text>
          <List.Root>
            <List.Item>By email: feline.ada24@gmail.com</List.Item>
          </List.Root>
        </Stack>
      </Stack>
    </Stack>
  );
};

export default PrivacePolicy;
